version: '3'

services:
  postgres:
    container_name: santa_cruz_postgres
    image: postgres:12.3
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=santa_cruz
      - POSTGRES_USER=santa_cruz_user
      - POSTGRES_PASSWORD=santa_cruz_password
