[package]
name = "santa_cruz_codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0"
prost = "0.10"
rustfmt = "0.10.0"
prost-types = "0.10"
convert_case = "0.5"
